AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: geo-jobs - Computation and API

Globals:
  Function:
    CodeUri: .
    Runtime: java17
    Tracing: Active
    Architectures:
      - x86_64
    Timeout: 600
    EventInvokeConfig:
      MaximumRetryAttempts: 0
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    VpcConfig:
      SecurityGroupIds:
        - !Sub '{{resolve:ssm:/bpartners-imagery/sg/id}}'
      SubnetIds:
        - !Sub '{{resolve:ssm:/bpartners-imagery/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/bpartners-imagery/private/subnet2/id}}'
    Environment:
      Variables:
        ENV: !Ref Env
        AWS_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/geo-jobs/${Env}/sqs/mailbox-queue-url}}'
        AWS_EVENTBRIDGE_BUS: !Sub '{{resolve:ssm:/geo-jobs/${Env}/eventbridge/bus-name}}'
        AWS_S3_BUCKET: !Sub '{{resolve:ssm:/geo-jobs/${Env}/s3/bucket-name}}'
        AWS_SES_SOURCE: lou@bpartners.app
        
        DATABASE_URL: !Sub '{{resolve:ssm:/geo-jobs/${Env}/db/url}}'
        DATABASE_USERNAME: !Sub '{{resolve:ssm:/geo-jobs/${Env}/db/user/username}}'
        DATABASE_PASSWORD: !Sub '{{resolve:ssm:/geo-jobs/${Env}/db/user/password}}'
        TILES_DOWNLOADER_API_URL: https://p36gjgisjpttscydepu3suuupi0wkute.lambda-url.eu-west-3.on.aws
        TILE_DETECTION_API_URL: https://3gl56b3gqs6cfynuzqkte2rthm0onaoh.lambda-url.eu-west-3.on.aws
        ADMIN_API_KEY: !Sub '{{resolve:ssm:/bpartners-geo-jobs/${Env}/admin/api-key}}'
        ANNOTATOR_API_URL: !Sub '{{resolve:ssm:/geo-jobs/${Env}/annotator/url}}'
        ANNOTATOR_API_KEY: !Sub '{{resolve:ssm:/geo-jobs/${Env}/annotator/api/key}}'
        ANNOTATOR_GEOJOBS_USER_INFO: !Sub '{{resolve:ssm:/geo-jobs/${Env}/annotator/user/info}}'
        TILES_DOWNLOADER_MOCK_ACTIVATED: !Sub '{{resolve:ssm:/geo-jobs/${Env}/tiles-downloader-activated}}'
        OBJECTS_DETECTOR_MOCK_ACTIVATED: !Sub '{{resolve:ssm:/geo-jobs/${Env}/objects-detector-activated}}'
        

Parameters:
  Env:
    Type: String

Resources:
  FrontalServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"

  FrontalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.bpartners.geojobs.ApiEventHandler::handleRequest
      MemorySize: 512
      Role: !Sub '{{resolve:ssm:/geo-jobs/${Env}/execution/role-arn}}'
      
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: FrontalServerlessRestApi
      ReservedConcurrentExecutions: 250

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.bpartners.geojobs.MailboxEventHandler::handleRequest
      MemorySize: 512
      Role: !Sub '{{resolve:ssm:/geo-jobs/${Env}/execution/role-arn}}'
      
      Events:
        AllEvents:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/geo-jobs/${Env}/sqs/mailbox-queue-arn}}'
            BatchSize: 1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

  ApiUrlSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /geo-jobs/, !Ref Env, /api/url ] ]
      Type: String
      Value: !Sub "https://${FrontalServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !GetAtt ApiUrlSSM.Value
