/*
 * Image Annotation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package app.bpartners.annotator.endpoint.rest.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import app.bpartners.annotator.endpoint.rest.model.AnnotationReview;
import app.bpartners.annotator.endpoint.rest.model.ReviewStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * AnnotationBatchReview
 */
@JsonPropertyOrder({
  AnnotationBatchReview.JSON_PROPERTY_ID,
  AnnotationBatchReview.JSON_PROPERTY_ANNOTATION_BATCH_ID,
  AnnotationBatchReview.JSON_PROPERTY_REVIEWS,
  AnnotationBatchReview.JSON_PROPERTY_STATUS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T18:28:50.570918+01:00[Europe/Paris]")
public class AnnotationBatchReview implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_ANNOTATION_BATCH_ID = "annotationBatchId";
  private String annotationBatchId;

  public static final String JSON_PROPERTY_REVIEWS = "reviews";
  private List<AnnotationReview> reviews = null;

  public static final String JSON_PROPERTY_STATUS = "status";
  private ReviewStatus status = ReviewStatus.ACCEPTED;


  public AnnotationBatchReview id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public AnnotationBatchReview annotationBatchId(String annotationBatchId) {
    this.annotationBatchId = annotationBatchId;
    return this;
  }

   /**
   * Get annotationBatchId
   * @return annotationBatchId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ANNOTATION_BATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAnnotationBatchId() {
    return annotationBatchId;
  }


  @JsonProperty(JSON_PROPERTY_ANNOTATION_BATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnnotationBatchId(String annotationBatchId) {
    this.annotationBatchId = annotationBatchId;
  }


  public AnnotationBatchReview reviews(List<AnnotationReview> reviews) {
    this.reviews = reviews;
    return this;
  }

  public AnnotationBatchReview addReviewsItem(AnnotationReview reviewsItem) {
    if (this.reviews == null) {
      this.reviews = new ArrayList<>();
    }
    this.reviews.add(reviewsItem);
    return this;
  }

   /**
   * Get reviews
   * @return reviews
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REVIEWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AnnotationReview> getReviews() {
    return reviews;
  }


  @JsonProperty(JSON_PROPERTY_REVIEWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReviews(List<AnnotationReview> reviews) {
    this.reviews = reviews;
  }


  public AnnotationBatchReview status(ReviewStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReviewStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(ReviewStatus status) {
    this.status = status;
  }


  /**
   * Return true if this AnnotationBatchReview object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnnotationBatchReview annotationBatchReview = (AnnotationBatchReview) o;
    return Objects.equals(this.id, annotationBatchReview.id) &&
        Objects.equals(this.annotationBatchId, annotationBatchReview.annotationBatchId) &&
        Objects.equals(this.reviews, annotationBatchReview.reviews) &&
        Objects.equals(this.status, annotationBatchReview.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, annotationBatchId, reviews, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnotationBatchReview {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    annotationBatchId: ").append(toIndentedString(annotationBatchId)).append("\n");
    sb.append("    reviews: ").append(toIndentedString(reviews)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

