AWSTemplateFormatVersion: "2010-09-09"
Description: geo-jobs-4 - Compute permission

Parameters:
  Env:
    Type: String

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '', [ geo-jobs-4-, !Ref Env, -ExecutionRole ] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  ExecutionRoleArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '',[ /geo-jobs-4/ , !Ref Env , /execution/role-arn ] ]
      Type: String
      Value: !GetAtt ExecutionRole.Arn
